#!/usr/bin/env bash

sudo -v

brew bundle --file=~/src/dotfiles/Brewfile

bash ~/src/dotfiles/.macos

ln -sf ~/src/dotfiles/.gitconfig ~/.gitconfig
ln -sf ~/src/dotfiles/.gitignore ~/.gitignore
ln -sf ~/src/dotfiles/config.fish ~/.config/fish/config.fish
ln -sf ~/src/dotfiles/bundler-config ~/.bundle/config
ln -sf ~/src/dotfiles/atom-config.cson ~/.atom/config.cson
ln -sf ~/src/dotfiles/.gemrc ~/.gemrc

if [[ $(dscl . -read /Users/`id -un`/ UserShell) =~ .*fish$ ]];
then
  echo "Shell already set to fish"
else
  echo `which fish` | sudo tee -a /etc/shells
  chsh -s `which fish`
fi
